config/routes.rb
Teamweb::Application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
      resources :organizations #do
        # resources :events do
        #   get 'add_user', on: :member

        #   resources :teams do
        #     get 'add_user', on: :member
        #   end
        # end
      #end
    end
  end

  resources :organizations do
    resources :seasons do
      resources :events do
        get 'add_user', on: :member
      end
      resources :teams do
        get 'add_user', on: :member
      end
    end
  end


# Special sans-organization event data
  match "new_event", to: "events#new_event", via: :all
  match "events", to: "events#create_event", via: :all
  match "all_events", to: "events#list", via: :all

  get "home/index"

  root :to => 'home#index'
end

app/models/season.rb
# == Schema Information
#
# Table name: seasons
#
#  id              :integer          not null, primary key
#  organization_id :integer
#  name            :string(255)      not null
#  start           :date
#  end             :date
#  members_allowed :boolean          default(TRUE), not null
#  max_members     :integer
#  teams_allowed   :boolean          default(TRUE), not null
#  max_teams       :integer
#  max_team_size   :integer
#  created_at      :datetime
#  updated_at      :datetime
#  self_organized  :boolean          default(TRUE)
#  seasons_allowed :boolean          default(FALSE)
#

class Season < ActiveRecord::Base
  include Groupable
  belongs_to :organization
  has_many :events, dependent: :destroy
  has_many :teams, dependent: :destroy
  validates :name, presence: true, uniqueness: {case_sensitive: false, scope: :organization_id}, length: {in: 2..40}
  validates_numericality_of :max_team_size, allow_nil: true, greater_than: 0
  validates_numericality_of :max_teams, allow_nil: true, greater_than: 0, if: -> {self.teams_allowed?}
  validates_numericality_of :max_members, allow_nil: true, greater_than: 0, if: -> {self.members_allowed?}  
  alias_attribute :season_name, :name
  alias_attribute :season_start, :start
  alias_attribute :season_end, :end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_parents
  before_action :set_season, only: [:show, :edit, :update, :destroy]
  
  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.order(:name).page params[:page]
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = @organization.seasons.build(params[:season])
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = @organization.seasons.build(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to [@organization, @season], notice: 'Season was successfully created.' }
        format.json { render action: 'show', status: :created, location: @season }
      else
        format.html { render action: 'new' }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to [@organization, @season], notice: 'Season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to organization_seasons_url }
      format.json { head :no_content }
    end
  end

  private
    def set_season
      @season = Season.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_parents
      @organization = Organization.friendly.find(params[:organization_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:name, :start, :end, :members_allowed, :max_members, :teams_allowed, :max_teams, :max_team_size)
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_buttons.html.haml
%td.btn-group.col-md-6.visible-md.visible-lg
  = link_to bs_icon_tag("play") + 'Show', organization_season_path(season.organization, season), class: "btn btn-info"
  = link_to icon_tag("bell") + "Events", organization_season_events_path(season.organization, season), class: "btn btn-info"
  - if season.teams_allowed?
    = link_to fa_icon_tag("flag") + 'Teams', organization_season_teams_path(season.organization, season), class: "btn btn-info"
  - else
    = link_to fa_icon_tag("flag") + 'Teams', "#", class: "btn btn-info", disabled: "disabled"    
  - if user_signed_in?
    = link_to bs_icon_tag("wrench") + 'Edit', edit_organization_season_path(season.organization, season), class: "btn btn-info"
    = link_to bs_icon_tag("trash") + 'Delete', organization_season_path(season.organization, season), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger"
%td.col-xs-3.hidden-md.hidden-lg
  .btn-group
    %button{:class =>"btn btn-info dropdown-toggle", :"data-toggle" => "dropdown"}
      Actions
      %span.caret
    %ul.dropdown-menu{role:"menu"}
      %li 
        = link_to bs_icon_tag("play") + 'Show', organization_season_path(season.organization, season)
        = link_to icon_tag("bell") + 'Events', organization_season_events_path(season.organization, season)
      - if season.teams_allowed?
        %li
          = link_to bs_icon_tag("flag") + 'Teams', organization_season_teams_path(season.organization, season)
      - if user_signed_in?
        %li
          = link_to bs_icon_tag("wrench") + 'Edit', edit_organization_season_path(season.organization, season)
        %li
          = link_to bs_icon_tag("trash") + 'Delete', organization_season_path(season.organization, season), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/seasons/_form.html.haml
= simple_form_for [@organization, @season] do |f|
  -#= f.error_notification
  - if @season.errors.any?
    %h2= "#{pluralize(@season.errors.count, "error")} prohibited this team from being saved:"
    %ul
      - @season.errors.full_messages.each do |msg|
        %li= msg

  .form-inputs
    = f.input :name, label: "Name for this season"
    = f.input :start, as: :string, input_html: { type: "date"}
    = f.input :end, as: :string, input_html: { type: "date" }
    = f.input :members_allowed, label: "Members allowed?", hint: "Can users join the season without a team?", input_html: { :'data-hide' => '.season_max_members'}
    = f.input :max_members, input_html: { :'data-maxable' => 'no-max'}
    = f.input :teams_allowed, label: "Teams allowed?", hint: "Can users create teams?", input_html: { :'data-hide' => '.season_max_teams, .season_max_team_size'}
    = f.input :max_teams, input_html: { :'data-maxable' => 'no-max'}
    = f.input :max_team_size, input_html: { :'data-maxable' => 'no-max'}

  .form-actions
    %button.btn.btn-info{type: "submit"}
      = icon_tag('thumbs-up') + 'Save'

app/views/seasons/edit.html.haml
%h1 Editing season

= render 'form'

= link_to 'Show', organization_season_path(@season.organization, @season) 
\|
= link_to 'Back', organization_seasons_path

app/views/seasons/index.html.haml
%h1 
  = @organization.name.possessive + " Season".pluralize(@seasons.count)

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Start
      %th End
      %th

  - @seasons.each do |season|
    %tr
      %td= season.name
      %td= season.start
      %td= season.end
      = render partial: 'buttons', locals: {season: season}
      
%br

= link_to icon_tag("star-empty") + 'New Season', new_organization_season_path, class: "btn btn-success" if user_signed_in?
= paginate @seasons

app/views/seasons/new.html.haml
%h1 New season

= render 'form'

= link_to 'Back', organization_seasons_path

app/views/seasons/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @season.name
%p
  %b Start:
  = @season.start
%p
  %b End:
  = @season.end
%p
  %b Members allowed:
  = @season.members_allowed
%p
  %b Max members:
  = @season.max_members
%p
  %b Teams allowed:
  = @season.teams_allowed
%p
  %b Max teams:
  = @season.max_teams
%p
  %b Max team size:
  = @season.max_team_size

= link_to 'Edit', edit_organization_season_path(@organization, @season)
\|
= link_to 'Back', organization_seasons_path