config/routes.rb
Teamweb::Application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
      resources :organizations #do
        # resources :events do
        #   get 'add_user', on: :member

        #   resources :teams do
        #     get 'add_user', on: :member
        #   end
        # end
      #end
    end
  end

  resources :organizations do
    resources :seasons do
      resources :events do
        get 'add_user', on: :member
      end
      resources :teams do
        get 'add_user', on: :member
      end
    end
  end


# Special sans-organization event data
  match "new_event", to: "events#new_event", via: :all
  match "events", to: "events#create_event", via: :all
  match "all_events", to: "events#list", via: :all

  get "home/index"

  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @upcoming_events = Event.future.order(:start).limit(5)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
/ Jumbotron
.jumbotron
  %h1 Events Made Easy!
  %p.lead Organize and share your competitive events for FREE!
  = link_to "Create Events", new_event_path, class: "btn btn-lg btn-success"
  = link_to "View Events", all_events_path, class: "btn btn-lg btn-primary"
%hr/
/ columns
.row
  .col-md-4
    %h2 Upcoming Events
    %ul.events-list
      - @upcoming_events.each do |event|
        %li.clearfix 
          %abbr{title: event.start.format_like("Jan 1st 2001")}
            = event.name
          -#= link_to icon_tag("play") + "Info", organization_event_path(event.organization, event), class: "btn btn-info btn-small pull-right"
  .col-md-4
    %h2 Heading
    %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
    %p
      %a.btn{:href => "#"} View details &raquo;
  .col-md-4
    %h2 Heading
    %p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.
    %p
      %a.btn{:href => "#"} View details &raquo;
%hr/