config/routes.rb
Teamweb::Application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
      resources :organizations #do
        # resources :events do
        #   get 'add_user', on: :member

        #   resources :teams do
        #     get 'add_user', on: :member
        #   end
        # end
      #end
    end
  end

  resources :organizations do
    resources :seasons do
      resources :events do
        get 'add_user', on: :member
      end
      resources :teams do
        get 'add_user', on: :member
      end
    end
  end


# Special sans-organization event data
  match "new_event", to: "events#new_event", via: :all
  match "events", to: "events#create_event", via: :all
  match "all_events", to: "events#list", via: :all

  get "home/index"

  root :to => 'home#index'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  about      :string(255)
#  location   :string(255)
#  start      :date
#  end        :date
#  created_at :datetime
#  updated_at :datetime
#  latitude   :float
#  longitude  :float
#  gmaps      :boolean
#  season_id  :integer
#

class Event < ActiveRecord::Base
  include Groupable
  belongs_to :season
  has_many :matchups, dependent: :destroy
  has_many :teams, through: :matchups
  validates :name, presence: true, uniqueness: {case_sensitive: false, scope: :season_id}, length: {in: 2..255}
  validates :location, presence: true
  acts_as_gmappable process_geocoding: :geocode?, address: "location", normalized_address: "location", msg: "Google doesn't know where that is."

  scope :future, -> { where("start > ?", Time.zone.now)}

  def geocode?
    (!location.blank? && (latitude.blank? || longitude.blank?)) || location_changed?
  end

  def organization
    self.season.organization
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_parents, except: [:list, :new_event, :create_event]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :add_user]

  def add_user
    # Only add user if they won't blow out team size.
    if @event.add_event_member(current_user) 
      message = {notice: 'You have been added to the event!'}
    else
      message = {alert: 'This event is full and cannot accept any new members.'}
    end
    redirect_to [@organization, @event], message 
  end

  def list
    @events = Event.order(:name).page params[:page]
  end

  def new_event
    @event_form = session[:event_form] || EventForm.new
  end

  def create_event
    @event_form = EventForm.new(params[:event])
    if user_signed_in?
      if @event_form.save
        session.delete(:event_form) # remove session data if it exists
        redirect_to [@event_form.organization, @event_form.season, @event_form.event], notice: 'Event was successfully created.' 
      end
    else
      session[:event_form] = @event_form
      redirect_to new_user_registration_path
    end
  end

  def index
    @events = @season.events.order(:name).page params[:page]
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @maps_json = @event.to_gmaps4rails do |event, marker|
      marker.title event.name 
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = @season.events.build(params[:event])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = @season.events.new(event_params)

    Event.transaction do
      respond_to do |format|
        if @event.save
          # Automatically add creator as admin
          @event.members.add_member(current_user, admin_flag: true)
          format.html { redirect_to [@season.organization, @season, @event], notice: 'Event was successfully created.' }
          format.json { render json: [@season.organization, @season, @event], status: :created, location: @event }
        else
          format.html { render action: "new" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end 
    end # end transaction
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update_attributes(event_params)
        format.html { redirect_to [@organization, @season, @event], notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to organization_season_events_url }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def set_parents
      @season = Season.find(params[:season_id])
      @organization = @season.organization
    end

    def event_params
      params.require(:event).permit(:about, :end, :location, :name, :start)
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def badge(word, count)
    "#{word} <span class='badge badge-info'>#{count}</span>".html_safe
  end 

end

app/views/events/_buttons.html.haml
%td.btn-group.col-md-5.visible-md.visible-lg
  = link_to bs_icon_tag("play") + 'Show', organization_season_event_path(event.organization, event.season, event), class: "btn btn-info"
  - if event.season.teams_allowed?
    = link_to bs_icon_tag("flag") + 'Teams', organization_season_teams_path(event.organization, event.season, event), class: "btn btn-info"
  - else
    = link_to bs_icon_tag("flag") + 'Teams', "#", class: "btn btn-info", disabled: "disabled"    
  - if user_signed_in?
    = link_to bs_icon_tag("wrench") + 'Edit', edit_organization_season_event_path(event.organization, event.season, event), class: "btn btn-info"
    = link_to bs_icon_tag("trash") + 'Delete', organization_season_event_path(event.organization, event.season, event), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger"
%td.col-xs-2.hidden-md.hidden-lg
  .btn-group
    %button{:class =>"btn btn-info dropdown-toggle", :"data-toggle" => "dropdown"}
      Actions
      %span.caret
    %ul.dropdown-menu{role:"menu"}
      %li 
        = link_to bs_icon_tag("play") + 'Show', organization_season_event_path(event.organization, event.season, event)
      - if event.season.teams_allowed?
        %li
          = link_to bs_icon_tag("flag") + 'Teams', organization_season_teams_path(event.organization, event.season, event)
      - if user_signed_in?
        %li
          = link_to bs_icon_tag("wrench") + 'Edit', edit_organization_season_event_path(event.organization, event.season, event)
        %li
          = link_to bs_icon_tag("trash") + 'Delete', organization_season_event_path(event.organization, event.season, event), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/events/_event_form.html.haml
= simple_form_for @event_form do |f|
  - if @event_form.errors.any?
    %h2= "#{pluralize(@event_form.errors.count, "error")} prohibited this event from being saved:"
    %ul
      - @event_form.errors.full_messages.each do |msg|
        %li= msg

  = f.input :name, label: "Name for this event", required: true
  = f.input :location, label: "Location of event", required: true
  = f.input :about, label: "Describe the event", as: :text, input_html: { class: "wysihtml5"}
  = f.input :start, as: :string, input_html: { type: "datetime-local"}
  = f.input :end, as: :string, input_html: { type: "datetime-local" }

  = f.input :seasons_allowed, as: :boolean, label: "Season?", hint: "Is this event part of a season?", input_html: { :'data-hide' => '.season_info'}
  
  .season_info
    = f.input :season_name, required: true
    = f.input :season_start, input_html: { type: "date"}
    = f.input :season_end, input_html: { type: "date"}

  = f.input :members_allowed, as: :boolean, label: "Members allowed?", hint: "Can users join the season without a team?", input_html: { :'data-hide' => '.event_max_members'}
  = f.input :max_members, as: :integer, input_html: { :'data-maxable' => 'no-max'}
  = f.input :teams_allowed, as: :boolean, label: "Teams allowed?", hint: "Can users create teams?", input_html: { :'data-hide' => '.event_max_teams, .event_max_team_size'}
  = f.input :max_teams, as: :integer, input_html: { :'data-maxable' => 'no-max'}
  = f.input :max_team_size, as: :integer, input_html: { :'data-maxable' => 'no-max'}

  = f.input :self_organized, as: :radio_buttons, label: "Event Owner", collection: [["Me", true], ["Organization", false]], hint: "Is this event by you or your organization?", input_html: { :'data-org' => '.org_info'}

  .org_info
    = f.input :org_name, label: "Organization Name", required: true
    = f.input :org_about, as: :text, label: "About the Organization", input_html: { class: "wysihtml5"}
    = f.input :org_location, label: "Organization Location"
    = f.input :contact, label: "Organization Contact", required: true

  .actions
    %button.btn.btn-info{type: "submit"}
      = icon_tag('thumbs-up') + 'Save'

app/views/events/_form.html.haml
= simple_form_for [@organization, @season, @event] do |f|
  - if @event.errors.any?
    %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
    %ul
      - @event.errors.full_messages.each do |msg|
        %li= msg

  = f.input :name, label: "Name for this event"
  = f.input :location, label: "Location of event"
  = f.input :about, label: "Describe the event", as: :text, input_html: { class: "wysihtml5"}
  = f.input :start, as: :string, input_html: { type: "datetime-local"}
  = f.input :end, as: :string, input_html: { type: "datetime-local" }

  .actions
    %button.btn.btn-info{type: "submit"}
      = icon_tag('thumbs-up') + 'Save'

app/views/events/_tab_details.haml
/ Details with tabs
%ul.nav.nav-tabs#eventTab
  %li.active
    = link_to "Info", "#info", :'data-toggle' => 'tab'
  - if @season.teams_allowed?
    %li
      = link_to badge("Teams", @event.teams.size), "#teams", :'data-toggle' => 'tab'
  - if @season.members_allowed?
    %li
      = link_to badge("Members", @event.members.size), "#members", :'data-toggle' => 'tab'
.tab-content#eventTabContent
  .tab-pane.fade.in.active#info
    = LiterateRandomizer.paragraphs(paragraphs: 4)
  - if @event.teams.count > 0
    .tab-pane.fade#teams
      %ol
        - @event.teams.each do |team|
          %li
            = link_to team.name, organization_season_team_path(@organization, @season, team)

  .tab-pane.fade#members
    %ol
      - @event.members.each do |member|
        %li
          = "#{member.user.name} - #{member.user.email}"
          - if member.admin
            %span.badge.badge-success
              Admin

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

.btn-group
  = link_to icon_tag("hand-left") + 'Back', organization_season_events_path, class: "btn btn-primary"
  = link_to icon_tag("play") + 'Show', organization_season_event_path(@event.organization, @event.season, @event), class: "btn btn-info"
  

app/views/events/index.html.haml
%h1 
  = @season.name + " Event".pluralize(@events.count)

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Location
      %th Start
      %th

  - @events.each do |event|
    %tr
      %td= event.name
      %td= event.location
      %td= event.start.try(:format_like, "Jan 1st")
      = render partial: 'buttons', locals: {event: event}

%br

= link_to icon_tag("star-empty") + 'New Event', new_organization_season_event_path, class: "btn btn-success" if user_signed_in?
= paginate @events

app/views/events/list.html.haml
%h1 All Events 

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th.hidden-xs Organization
      %th Location
      %th Start
      %th

  - @events.each do |event|
    %tr
      %td= event.name
      %td.hidden-xs= link_to event.season.name, organization_seasons_path(event.season.organization)
      %td= event.location
      %td= event.start.try(:format_like, "Jan 1st")
      = render partial: 'buttons', locals: {event: event}

%br
= paginate @events

app/views/events/new.html.haml
%h1 New event

= render 'form'
= link_to 'Back', organization_season_events_path

app/views/events/new_event.html.haml
%h1 Create Your Event

= render 'event_form'

app/views/events/show.html.haml
%h1
  = @event.name
.col-md-8{style: "min-height:450px;"}
  .col-md-5
    %p
      %strong About:
      = @event.about
  .col-md-offset-2.col-md-5.well
    %p
      %strong Start Date:
      = @event.start.try(:format_like, "Jan 1st 2000")
    %p
      %strong End Date:
      = @event.end.try(:format_like, "Jan 1st 2000")
  %h4{style: "clear: left;"}
    %strong Event Details

  = render 'tab_details'

/ Map    
.col-md-4
  = gmaps4rails(@maps_json)
  %p
    %strong Location
    = @event.location

/ Organization Info
.well.col-md-4
  %h4 Organization info
  %p
    %strong
      = @organization.name
  %p
    = @organization.about
  %p
    = @organization.contact

/ Button bar
.col-md-12
  .btn-group
    = link_to icon_tag("hand-left") + 'Back', organization_season_events_path, class: "btn btn-primary"
    = link_to icon_tag("wrench") + 'Edit', edit_organization_season_event_path(@season.organization, @season, @event), class: "btn btn-info"
    = link_to 'Add me to event', add_user_organization_season_event_path(@organization, @season, @event), class: "btn btn-info"