config/routes.rb
Teamweb::Application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
      resources :organizations #do
        # resources :events do
        #   get 'add_user', on: :member

        #   resources :teams do
        #     get 'add_user', on: :member
        #   end
        # end
      #end
    end
  end

  resources :organizations do
    resources :seasons do
      resources :events do
        get 'add_user', on: :member
      end
      resources :teams do
        get 'add_user', on: :member
      end
    end
  end


# Special sans-organization event data
  match "new_event", to: "events#new_event", via: :all
  match "events", to: "events#create_event", via: :all
  match "all_events", to: "events#list", via: :all

  get "home/index"

  root :to => 'home#index'
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  about      :string(255)
#  location   :string(255)
#  contact    :string(255)
#  created_at :datetime
#  updated_at :datetime
#  slug       :string(255)
#

class Organization < ActiveRecord::Base
  extend FriendlyId
  include Groupable
  friendly_id :name, use: :slugged
  has_many :seasons, dependent: :destroy
  validates :name, :contact, presence: true, length: {in: 2..38}
  alias_attribute :org_name, :name
  alias_attribute :org_about, :about
  alias_attribute :org_location, :location
end

app/controllers/api/v1/organizations_controller.rb
module Api
  module V1
    class OrganizationsController < ApplicationController
      respond_to :json
      before_filter :authenticate_user_from_token!

      def index
        @organizations = Organization.order(:name)
      end

      def show
        @organization = Organization.friendly.find(params[:id])
      end
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_org, only: [:show, :edit, :update, :destroy]
  #def index
  #  @organizations = Organization.all

  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.json { render json: @organizations }
  #  end
  #end
  def index
    @organizations = Organization.order(:name).page params[:page]
  end

  def show
    # TODO rethink this
    # @maps_json = @organization.seasons.first.events.to_gmaps4rails do |event, marker|
    #   marker.title event.name 
    # end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end


  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    Organization.transaction do
      respond_to do |format|
        if @organization.save
          # Automatically add creator as admin
          @organization.members.add_member(current_user, admin_flag: true)

          format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
          format.json { render json: @organization, status: :created, location: @organization }
        else
          format.html { render action: "new" }
          format.json { render json: @organization.errors, status: :unprocessable_entity }
        end
      end
    end # end transaction
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update_attributes(organization_params)
        format.html { redirect_to organization_path(@organization), notice: 'Organization was successfully updated.'}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private

    def set_org
      @organization = Organization.friendly.find(params[:id])
    end

    def organization_params
      params.require(:organization).permit(:about, :contact, :location, :name)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_buttons.html.haml
%td.btn-group.col-md-6.visible-md.visible-lg
  = link_to icon_tag("play") + 'Show', org, class: "btn btn-info"
  = link_to icon_tag("calendar") + 'Seasons', organization_seasons_path(org), class: "btn btn-info"
  - if user_signed_in?
    = link_to icon_tag("wrench") + 'Edit', edit_organization_path(org), class: "btn btn-info"
    = link_to icon_tag("trash") + 'Delete', org, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger"
%td.col-xs-3.hidden-md.hidden-lg
  .btn-group
    %button{:class =>"btn btn-info dropdown-toggle", :"data-toggle" => "dropdown"}
      Actions
      %span.caret
    %ul.dropdown-menu{role:"menu"}
      %li 
        = link_to bs_icon_tag("play") + 'Show', org
        = link_to icon_tag("calendar") + 'Seasons', organization_seasons_path(org)
      - if user_signed_in?
        %li
          = link_to bs_icon_tag("wrench") + 'Edit', edit_organization_path(org)
        %li
          = link_to bs_icon_tag("trash") + 'Delete', org, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/organizations/_form.html.haml
= simple_form_for @organization do |f|
  - if @organization.errors.any?
    %h2= "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
    %ul
      - @organization.errors.full_messages.each do |msg|
        %li= msg

  = f.input :name
  = f.input :about, label: "Describe the event", as: :text, input_html: { class: "wysihtml5"}
  = f.input :location
  = f.input :contact
  .actions
    %button.btn.btn-info{type: "submit"}
      = icon_tag('thumbs-up') + 'Save'

app/views/organizations/edit.html.haml
%h1 Editing Organization

= render 'form'

.btn-group
  = link_to icon_tag("hand-left") + 'Back', organizations_path, class: "btn btn-primary"
  = link_to icon_tag("play") + 'Show', @organization, class: "btn btn-info"
  

app/views/organizations/index.html.haml
%h1 Organizations

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Location
      %th Contact
      %th

  - @organizations.each do |org|
    %tr
      %td= org.name
      %td= org.location
      %td= org.contact
      = render partial: 'buttons', locals: {org: org}

%br

= link_to icon_tag("star-empty") + 'New Organization', new_organization_path, class: "btn btn-success" if user_signed_in?

app/views/organizations/new.html.haml
%h1 New Organization

= render 'form'

= link_to 'Back', organizations_path

app/views/organizations/show.html.haml
.page-header
  %h1 
    Organization
    = @organization.name
.col-md-5
  %p
    %strong About:
    = @organization.about
  %p
    %strong Location:
    = @organization.location
  %p
    %strong Main Contact:
    = @organization.contact
.col-md-6
  %p
    %strong Members
    %ol
      - @organization.members.each do |member|
        %li 
          = "#{member.user.name} - #{member.user.email}"
          - if member.admin
            %span.badge.badge-success
              Admin
.col-md-11
  %strong
    = link_to "#{@organization.name} Seasons", organization_seasons_path(@organization)
  %span.badge 
    = @organization.seasons.count
  = gmaps4rails(@maps_json)

  .btn-group.pull-left
  = link_to icon_tag("hand-left") + 'Back', organizations_path, class: "btn btn-primary"
  = link_to icon_tag("wrench") + 'Edit', edit_organization_path(@organization), class: "btn btn-info"
  